spring:
  profiles:
    include: local
    active: local

  data:
    redis:
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      port: ${REDIS_PORT}
      connect-timeout: 5000
      timeout: 3000
  lifecycle:
    timeout-per-shutdown-phase: 1s
  jackson:
    time-zone: America/New_York

logging:
  level:
    live.gloticker: DEBUG
    org.springframework.data.redis: INFO

server:
  port: 8080
  shutdown: graceful

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_API_URL}
