spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      connect-timeout: 5000
      timeout: 3000
  lifecycle:
    timeout-per-shutdown-phase: 1s

logging:
  level:
    live.gloticker: DEBUG
    org.springframework.data.redis: INFO

server:
  port: 8081
  shutdown: graceful
